export interface Elem {
  /** A UUID generated by the adapter for the source DOM node. */
  id: string;

  /** The raw text value extracted from the source DOM node. */
  value: string;
}

export interface ProductInfo {
  name: Elem;
  originalPrice?: Elem;
  currentPrice?: Elem;
  discount?: Elem;
  image?: Elem;
  description?: Elem;
  stockAmount?: Elem;
}
